CONFIG_TOOLCHAIN_NAME=		esp-open-sdk
CONFIG_RTOS_NAME=		esp-open-rtos

CONFIG_REPOSITORY_SERVER=	http://github.com
CONFIG_TOOLCHAIN_USERNAME=	pfalcon
CONFIG_RTOS_USERNAME=		SuperHouse

CONFIG_BUILDSCRIPT_FILE_NAME=	Makefile

CONFIG_SRC_DIR_NAME=		src
CONFIG_BIN_DIR_NAME=		bin
CONFIG_FIRMWARE_DIR_NAME=	firmware
CONFIG_EXAMPLES_DIR_NAME=	examples
CONFIG_TOOLCHAIN_DIR_NAME=	xtensa-lx106-elf

CONFIG_TARGET_FILE_SUFFIX=	bin

CONFIG_TARGET_LOWER_FILE_NAME=	0x00000.$(CONFIG_TARGET_FILE_SUFFIX)

