FLASH_RULE_PREFIX=		flash

FLASH_AVAILABLE_FIRWARE_LIST=	$(wildcard \
					$(EXAMPLES_TARGET_LOWER_FILE_LIST))

FLASH_FIRMWARE_DIR=		$(CONFIG_FIRMWARE_DIR_NAME)/$(CONFIG_TARGET_LOWER_FILE_NAME)

FLASH_AVAILABLE_ID_LIST=	$(patsubst \
					$(INTERNAL_EXAMPLES_DIR)/%/$(FLASH_FIRMWARE_DIR), \
					%, \
					$(FLASH_AVAILABLE_FIRWARE_LIST))

FLASH_RULE_LIST=		$(addprefix \
					$(FLASH_RULE_PREFIX)_, \
					$(FLASH_AVAILABLE_ID_LIST))

