FLASH_RULE_PREFIX=		flash

FLASH_AVAILABLE_FIRWARE_LIST=	$(wildcard \
					$(EXAMPLES_TARGET_FILE_LIST))

FLASH_AVAILABLE_ID_LIST=	$(patsubst \
					$(INTERNAL_EXAMPLES_DIR)/%/$(EXAMPLES_TARGET_LOWER_FILE), \
					%, \
					$(FLASH_AVAILABLE_FIRWARE_LIST))

FLASH_RULE_LIST=		$(addprefix \
					$(FLASH_RULE_PREFIX)_, \
					$(FLASH_AVAILABLE_ID_LIST))

