INTERNAL_SRC_DIR=		$(CONFIG_SRC_DIR_NAME)

INTERNAL_TOOLCHAIN_DIR=		$(CONFIG_TOOLCHAIN_DIR_NAME)/$(CONFIG_BIN_DIR_NAME)

INTERNAL_TOOLCHAIN_SRC_DIR=	$(INTERNAL_SRC_DIR)/$(CONFIG_TOOLCHAIN_NAME)
INTERNAL_TOOLCHAIN_BIN_DIR=	$(INTERNAL_TOOLCHAIN_SRC_DIR)/$(INTERNAL_TOOLCHAIN_DIR)

INTERNAL_RTOS_SRC_DIR=		$(INTERNAL_SRC_DIR)/$(CONFIG_RTOS_NAME)

INTERNAL_EXAMPLES_DIR=		$(INTERNAL_RTOS_SRC_DIR)/$(CONFIG_EXAMPLES_DIR_NAME)

INTERNAL_WIFI_FILE_DIR=		$(INTERNAL_RTOS_SRC_DIR)/$(CONFIG_WIFI_CONFIG_FILE)

INTERNAL_TOOLCHAIN_BASE_URL=	$(CONFIG_REPOSITORY_SERVER)/$(CONFIG_TOOLCHAIN_USERNAME)
INTERNAL_TOOLCHAIN_FULL_URL=	$(INTERNAL_TOOLCHAIN_BASE_URL)/$(CONFIG_TOOLCHAIN_NAME)

INTERNAL_RTOS_BASE_URL=		$(CONFIG_REPOSITORY_SERVER)/$(CONFIG_RTOS_USERNAME)
INTERNAL_RTOS_FULL_URL=		$(INTERNAL_RTOS_BASE_URL)/$(CONFIG_RTOS_NAME)
